"""DOC-BACKTICK-GATE — every LIVE doc has a balanced backtick count.

An unbalanced backtick makes every downstream code-span scan misread the file: the
regex `` `([^`]+)` `` cannot pair across a stray backtick, so it silently consumes the
rest of the document as one giant "span" — exactly how `test_cli_reference.py`'s
`_doc_flags` once returned the empty set and let `test_every_documented_flag_exists`
pass vacuously (see that module's `_strip_fences` docstring). The file that regression
was originally measured in, `docs/PLAN.md`, is deleted (2026-08-14) — the evidence is
gone and nothing was ever recorded as fixing it. This is the gate that replaces it.

Same LIVE/HISTORY split as `test_doc_links.py`, for the same reason: a dated,
append-only record can legitimately narrate a backtick escape (`` ` `` inside a
double-backtick span, e.g. WORKLOG.md's own entry describing this exact defect) and
must never be rewritten to satisfy a gate added after the fact. Only LIVE docs — the
ones a reader navigates as *current* — fail the build. `graphify-out/` is excluded
outright: it is regenerated by `graphify update .`, never hand-authored, so there is
nothing for a doc-discipline gate to hold accountable.
"""
from __future__ import annotations

import re
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

# Mirrors test_doc_links.py's split: a dated, append-only record vs. a live surface.
HISTORY_DIRS = ("work/archive/", "work/regression/")
HISTORY_FILES = {"work/WORKLOG.md", "work/IMPLEMENTATION.md", "CHANGELOG.md"}
GENERATED_DIRS = ("graphify-out/",)

_FENCE = re.compile(r"^\s*(```|~~~)")


def _strip_fences(text: str) -> str:
    """Drop fenced blocks before any backtick-based scan — a fence is not a span."""
    out, fenced = [], False
    for line in text.splitlines():
        if _FENCE.match(line):
            fenced = not fenced
            continue
        if not fenced:
            out.append(line)
    return "\n".join(out)


def _is_history(path: str) -> bool:
    return path.startswith(HISTORY_DIRS) or path in HISTORY_FILES


def _is_generated(path: str) -> bool:
    return path.startswith(GENERATED_DIRS)


def _docs() -> list[str]:
    out = subprocess.run(("git", "-C", str(REPO), "ls-files", "*.md"),
                         capture_output=True, text=True, check=True).stdout
    return sorted(p for p in out.split("\n") if p and not _is_generated(p))


def _unbalanced(paths) -> list[tuple[str, int]]:
    bad = []
    for f in paths:
        count = _strip_fences((REPO / f).read_text(encoding="utf-8")).count("`")
        if count % 2 != 0:
            bad.append((f, count))
    return bad


def test_every_live_doc_has_balanced_backticks():
    """The gate. A stray backtick in a doc a reader navigates as current breaks every
    code-span scan downstream of it — silently, since nothing raises on the odd count
    itself, only on whatever later reads the doc and gets the wrong span."""
    bad = _unbalanced(f for f in _docs() if not _is_history(f))
    assert not bad, "unbalanced backtick count (after stripping fences) in LIVE docs:\n" + "\n".join(
        f"  {f}: {c} backticks" for f, c in bad)


def test_history_backtick_imbalance_is_bounded_and_known():
    """The exemption is a decision, so it states its own size — same reasoning as
    DOC-LINK-CHECK's dangle count. A HISTORY doc narrating a backtick escape (e.g. `` ` ``
    used to illustrate this exact defect) is expected; a HISTORY set that silently grew
    to swallow every imbalance would make the LIVE gate meaningless."""
    hist = _unbalanced(f for f in _docs() if _is_history(f))
    assert len(hist) < 5, (
        f"{len(hist)} HISTORY docs with an unbalanced backtick count — well past the 1 "
        "(WORKLOG.md) measured when this gate was added. Either a new kind of doc is "
        "landing in the HISTORY set or a LIVE doc regressed and was misclassified.")


def test_the_detector_actually_detects():
    """A gate is only worth having if it fires. Pin both regimes directly, independent
    of the current state of any real doc in the tree."""
    assert _strip_fences("one `stray` backtick: `oops").count("`") % 2 != 0
    assert _strip_fences("a matched `span` and another `one`").count("`") % 2 == 0
    # a stray backtick inside a fence is an illustration, not a citation — never counted
    balanced_via_fence = _strip_fences("```\n`unmatched\n```\ntext after")
    assert balanced_via_fence.count("`") % 2 == 0
